# Generated by Django 5.1 on 2025-05-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="cms_file",
            field=models.FileField(
                blank=True, null=True, upload_to="cms_sigs/%Y/%m/%d"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="signed_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="signed_pdfs/%Y/%m/%d"
            ),
        ),
    ]
